FactoryGirl.define do
  factory :ad_tag do
    ad_type                       "Large Skyscraper"
    advertiser                    "Widget"
    audience                      "Males who read My Magazine"
    cost_basis                    "3000"
    client_cost                   "3500"
    cost_method                   "CPM"
    days                          "Mon-Fri"
    details                       "Alway above fold"
    device                        "Desktop"
    end_date                      "1/1/2016"
    format                        "HTML5"
    height                        "600"
    impressions                   "1000000000"
    javascript_tag                "<script> console.log('Tag code here!!') </sscript>"
    publisher                     "Google"
    media_plan_name               "Best Campaign Ever (CTR through the roof!!)"
    placement                     "Google_My Magazine_Males 20-30_300x600"
    primary_target_audience       "Males 20-30"
    product                       "Magazine"
    properties                    "North America"
    size                          "300x600"
    site                          "mymagazine.com"
    start_action                  "auto"
    start_date                    "1/1/2015"
    total_cost                    "5,000"
    unit_cost                     "1.50"
    width                         "300"
    flight_id                     1
  end
end