import DS from 'ember-data';

export default DS.Model.extend({
  flight:                   DS.belongsTo('flight'),

  ad_type:                  DS.attr('string'),
  advertiser:               DS.attr('string'),
  audience:                 DS.attr('string'),
  cost_basis:               DS.attr('string'),
  client_cost:              DS.attr('string'),
  cost_method:              DS.attr('string'),
  days:                     DS.attr('string'),
  details:                  DS.attr('string'),
  device:                   DS.attr('string'),
  end_date:                 DS.attr('string'),
  format:                   DS.attr('string'),
  height:                   DS.attr('string'),
  impressions:              DS.attr('string'),
  javascript_tag:           DS.attr('string'),
  publisher:                DS.attr('string'),
  media_plan_name:          DS.attr('string'),
  placement:                DS.attr('string'),
  primary_target_audience:  DS.attr('string'),
  product:                  DS.attr('string'),
  properties:               DS.attr('string'),
  size:                     DS.attr('string'),
  site:                     DS.attr('string'),
  start_action:             DS.attr('string'),
  start_date:               DS.attr('string'),
  total_cost:               DS.attr('string'),
  unit_cost:                DS.attr('string'),
  width:                    DS.attr('string'),
  flight_id:                DS.attr('number'),
  created_at:               DS.attr('date'),
  updated_at:               DS.attr('date')
});