default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: r3act_development

test:
  <<: *default
  database: r3act_test

production:
  <<: *default
  database: r3act