default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: reactive_dashboard_development

test:
  <<: *default
  database: reactive_dashboard_test

production:
  <<: *default
  database: reactive_dashboard
